"""Radio tick engine for HomeAITuber.

Periodic radio segment generation loop.
Connects radio_prompt_builder → Speaker LLM → structured output → TTS → playback.

This is the core of Phase 1: the server-side scheduler that generates
EN → JP → EN_REPEAT bilingual radio segments on a configurable interval.

Design:
- Runs as an asyncio background task inside the Open-LLM-VTuber event loop
- Configurable interval (default: every 10 minutes = 600s)
- Each tick: build prompt → call LLM → parse structure → queue TTS → notify frontend
- Respects privacy doctrine: no WAN access, no filesystem scanning
"""

import asyncio
import json
import logging
import time
from datetime import datetime, timezone
from pathlib import Path
import re
from typing import Callable, Optional

logger = logging.getLogger(__name__)

# Default radio interval: 10 minutes
DEFAULT_RADIO_INTERVAL_SECONDS = 600


class RadioSegment:
    """A single radio segment generated by the Speaker LLM.

    Supports expanded format with mood, extra, and sub-segments array.
    """

    def __init__(self, data: dict):
        self.segment_id = data.get("segment_id", f"radio-{datetime.now().strftime('%Y%m%d-%H%M%S')}")
        self.en = data.get("en", "")
        self.jp = data.get("jp", "")
        self.en_repeat = data.get("en_repeat", "")
        self.phrase = data.get("phrase", "")
        self.note = data.get("note", "")
        self.topic = data.get("topic", "general")
        self.mood = data.get("mood", "brisk")  # chaotic | chill | brisk | thoughtful
        self.extra = data.get("extra", "")  # optional side note / joke
        self.segments = data.get("segments", [])  # sub-segment mini-show flow
        self.story_segment = data.get("story_segment", "")  # narrative line
        self.safety = data.get("safety", {"uses_private_data": False, "requires_external_access": False})
        self.timestamp = datetime.now(timezone.utc).isoformat()

    def to_playback_order(self) -> list[dict]:
        """Return segments in playback order.

        If sub-segments exist, play those first, then the main segment with phrase.
        Otherwise play the original EN → JP → EN_REPEAT flow.
        """
        parts = []

        # Play mini-show sub-segments if available
        if self.segments:
            for i, sub in enumerate(self.segments):
                en_text = sub.get("en", "")
                jp_text = sub.get("jp", "")
                if en_text:
                    parts.append({"type": "speak", "text": en_text, "lang": "en"})
                    parts.append({"type": "pause", "duration_ms": 400})
                if jp_text:
                    parts.append({"type": "speak", "text": jp_text, "lang": "jp"})
                    parts.append({"type": "pause", "duration_ms": 400})
            # Slightly longer pause before main content
            parts.append({"type": "pause", "duration_ms": 600})
        else:
            # Original flow: main EN → JP → EN_REPEAT
            if self.en:
                parts.append({"type": "speak", "text": self.en, "lang": "en"})
                parts.append({"type": "pause", "duration_ms": 800})
            if self.jp:
                parts.append({"type": "speak", "text": self.jp, "lang": "jp"})
                parts.append({"type": "pause", "duration_ms": 600})
            if self.en_repeat:
                parts.append({"type": "speak", "text": self.en_repeat, "lang": "en", "slow": True})

        # Phrase + note
        if self.phrase and self.note:
            parts.append({"type": "pause", "duration_ms": 500})
            parts.append({"type": "speak", "text": self.phrase, "lang": "en"})
            parts.append({"type": "speak", "text": self.note, "lang": "jp"})

        # Story segment (narrative mode)
        if self.story_segment:
            parts.append({"type": "pause", "duration_ms": 400})
            parts.append({"type": "speak", "text": self.story_segment, "lang": "en", "slow": True})

        return parts

    def to_dict(self) -> dict:
        return {
            "segment_id": self.segment_id,
            "en": self.en,
            "jp": self.jp,
            "en_repeat": self.en_repeat,
            "phrase": self.phrase,
            "note": self.note,
            "topic": self.topic,
            "mood": self.mood,
            "extra": self.extra,
            "segments": self.segments,
            "story_segment": self.story_segment,
            "safety": self.safety,
            "timestamp": self.timestamp,
        }


class RadioTickEngine:
    """Background engine that periodically generates radio segments.

    Integration points:
    - LLM client: any OpenAI-compatible chat completions endpoint
    - TTS callback: called with (text, lang) for each speak part
    - Notify callback: called with RadioSegment dict when a segment is produced
    """

    def __init__(
        self,
        soul_dir: Path,
        llm_client=None,  # OpenAI-compatible client
        llm_model: str = "Gemma-4-26B-A4B-it-NVFP4A16",
        llm_base_url: str = "http://100.89.160.90:30099/v1",
        llm_api_key: str = "",
        interval_seconds: int = DEFAULT_RADIO_INTERVAL_SECONDS,
        tts_callback: Optional[Callable] = None,
        notify_callback: Optional[Callable] = None,
        mattermost_callback: Optional[Callable] = None,
    ):
        from homeaituber.radio_prompt_builder import RadioPromptBuilder

        self.builder = RadioPromptBuilder(soul_dir)
        self.llm_client = llm_client
        self.llm_model = llm_model
        self.llm_base_url = llm_base_url
        self.llm_api_key = llm_api_key
        self.interval = interval_seconds
        self.tts_callback = tts_callback
        self.notify_callback = notify_callback
        self.mattermost_callback = mattermost_callback

        self._task: Optional[asyncio.Task] = None
        self._running = False
        self._last_segment: Optional[RadioSegment] = None
        self._language_mode: Optional[str] = None

    async def generate_segment(self, user_command: Optional[str] = None, mood: Optional[str] = None, language_mode: Optional[str] = None) -> Optional[RadioSegment]:
        """Generate a single radio segment: build prompt → call LLM → parse output.

        Args:
            user_command: Optional trigger command from user
            mood: Optional mood override (chaotic | chill | brisk | thoughtful)
            language_mode: Optional language mode override

        Returns RadioSegment on success, None on failure.
        """
        prompt = self.builder.build_radio_prompt(user_command=user_command, mood=mood, language_mode=language_mode)

        try:
            from openai import OpenAI

            client = self.llm_client
            if client is None:
                client = OpenAI(
                    base_url=self.llm_base_url,
                    api_key=self.llm_api_key or "sk-local",
                )

            # Atlas/Gemma-4 doesn't support response_format properly
            # Use a strong system prompt instead.
            t_start = time.time()
            response = client.chat.completions.create(
                model=self.llm_model,
                messages=[
                    {"role": "system", "content": "You are a home AITuber radio host. Output ONLY valid JSON matching the requested format. No markdown, no code fences, no extra text."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.85,
                max_tokens=512,
                stream=False,
            )
            t_llm = time.time() - t_start

            raw = response.choices[0].message.content
            usage = response.usage
            if usage:
                p_tok = usage.prompt_tokens
                c_tok = usage.completion_tokens
                tok_s = c_tok / t_llm if t_llm > 0 else 0
                logger.info(f"LLM generated {c_tok} tokens in {t_llm:.1f}s ({tok_s:.0f} tok/s, prompt={p_tok})")

            if not raw:
                logger.error("LLM returned empty response")
                return None

            raw = raw.strip()
            # Strip markdown code fences if present (```json ... ```)
            raw = re.sub(r'^```(?:json)?\s*\n?', '', raw)
            raw = re.sub(r'\n?```\s*$', '', raw)
            raw = raw.strip()

            # Parse JSON with decoder (for robustness against extra text)
            data = None
            for i, c in enumerate(raw):
                if c in ('{', '['):
                    try:
                        decoder = json.JSONDecoder()
                        obj, idx = decoder.raw_decode(raw, i)
                        data = obj
                        break
                    except json.JSONDecodeError:
                        continue
            if data is None:
                raise json.JSONDecodeError("No JSON object found in response", raw, 0)

            segment = RadioSegment(data)
            self._last_segment = segment
            logger.info(f"Radio segment generated: {segment.segment_id} topic={segment.topic} mood={segment.mood}")
            return segment

        except Exception as e:
            logger.error(f"Radio segment generation failed: {e}")
            return None

    async def _playback_segment(self, segment: RadioSegment) -> None:
        """Send segment through TTS callbacks."""
        if self.tts_callback:
            for part in segment.to_playback_order():
                if part["type"] == "speak":
                    try:
                        await self.tts_callback(part["text"], part["lang"])
                    except Exception as e:
                        logger.error(f"TTS playback failed: {e}")
                elif part["type"] == "pause":
                    await asyncio.sleep(part["duration_ms"] / 1000)

    async def _tick(self, language_mode: Optional[str] = None) -> None:
        """Execute one radio tick: generate segment → playback → notify."""
        logger.info("Radio tick starting...")
        segment = await self.generate_segment(language_mode=language_mode)
        if segment is None:
            logger.warning("Radio tick produced no segment")
            return

        # Playback via TTS
        await self._playback_segment(segment)

        # Notify frontend
        if self.notify_callback:
            try:
                await self.notify_callback(segment.to_dict())
            except Exception as e:
                logger.error(f"Notify callback failed: {e}")

        # Post to Mattermost
        if self.mattermost_callback:
            try:
                await self.mattermost_callback(segment)
            except Exception as e:
                logger.error(f"Mattermost callback failed: {e}")

        logger.info(f"Radio tick complete: {segment.segment_id}")

    async def _run_loop(self) -> None:
        """Main background loop: tick → sleep → repeat."""
        self._running = True
        logger.info(f"Radio tick engine started (interval={self.interval}s)")

        try:
            # Fire an immediate first segment
            await self._tick(language_mode=self._language_mode)

            while self._running:
                await asyncio.sleep(self.interval)
                if not self._running:
                    break
                await self._tick(language_mode=self._language_mode)

        except asyncio.CancelledError:
            logger.info("Radio tick engine cancelled")
        except Exception as e:
            logger.error(f"Radio tick engine error: {e}")
        finally:
            self._running = False

    def start(self) -> None:
        """Start the radio tick background task."""
        if self._task is not None and not self._task.done():
            logger.warning("Radio tick engine already running")
            return
        self._task = asyncio.create_task(self._run_loop())

    async def stop(self) -> None:
        """Stop the radio tick engine."""
        self._running = False
        if self._task is not None:
            self._task.cancel()
            try:
                await self._task
            except asyncio.CancelledError:
                pass
            self._task = None
        logger.info("Radio tick engine stopped")

    def is_running(self) -> bool:
        return self._running

    def set_language_mode(self, language_mode: Optional[str]) -> None:
        """Update the language mode for subsequent auto-ticks."""
        self._language_mode = language_mode
        logger.info(f"Radio language mode set to: {language_mode}")

    def last_segment(self) -> Optional[RadioSegment]:
        return self._last_segment


# Convenience: standalone radio tick for CLI testing
async def generate_one_segment(
    soul_dir: str = "soul",
    llm_base_url: str = "http://100.89.160.90:30099/v1",
    llm_model: str = "Gemma-4-26B-A4B-it-NVFP4A16",
    llm_api_key: str = "sk-local",
    mood: Optional[str] = None,
) -> Optional[dict]:
    """Generate a single radio segment from the CLI. Useful for manual testing.

    Args:
        mood: Optional mood override (chaotic | chill | brisk | thoughtful)
    """
    engine = RadioTickEngine(
        soul_dir=Path(soul_dir),
        llm_base_url=llm_base_url,
        llm_model=llm_model,
        llm_api_key=llm_api_key,
    )
    segment = await engine.generate_segment(mood=mood)
    if segment:
        return segment.to_dict()
    return None


if __name__ == "__main__":
    # CLI test: python -m homeaituber.radio_tick --mood chaotic
    import argparse

    parser = argparse.ArgumentParser(description="Generate a radio segment")
    parser.add_argument("--mood", choices=["chaotic", "chill", "brisk", "thoughtful"], help="Mood override")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO)
    result = asyncio.run(generate_one_segment(mood=args.mood))
    if result:
        print(json.dumps(result, indent=2, ensure_ascii=False))
    else:
        print("Failed to generate segment")
